### PR TITLE
Rack 3

### PR DESCRIPTION
**Pull request by jnunemaker**
A few tweaks to help with rack 3 support. There might be more but I can't actually update until rails does and its currently locked to rack 2. Once rails git supports rack 3 I can update this PR and see if tests pass. 

xref #669

### CODE REVIEW

**Comment by n-rodriguez** [comment]
> There might be more but I can't actually update until rails does and its currently locked to rack 2

hmmm... weird.. I don't see the same thing :

Rails 7.0.4 :

```sh
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
```

**Comment by n-rodriguez** [comment]
> Once rails git supports rack 3 I can update this PR and see if tests pass.

https://github.com/rails/rails/pull/45741

**Comment by ericauv** [comment]
When is this expected to get merged?

**Comment by bkeepers** [comment]
Whenever Rack 3 support lands in Rails. See https://github.com/rails/rails/pull/46594

**Comment by ericauv** [comment]
Potentially related, let me know if this should be a separate issue -- is it possible to relax the `rack-protection` version to include up to `3.0.5` ?

**Comment by rgarver** [comment]
It looks like Rails edge is not supporting Rack 3: https://github.com/rails/rails/pull/48460

**Comment by bvogel** [comment]
the mentioned issue on rails was solved/merged, anything still in the way to get rack 3 support?

**Comment by bvogel** [comment]
@bkeepers YEAY!!! Thank you. 🎉

**Pull request merged**
