### PR TITLE
Add Rubocop

### PR DESCRIPTION
**Pull request by lazebny**
I added `rubocop` (https://github.com/backus/rubocop), `rubocop-rspec` (https://github.com/backus/rubocop-rspec) gems. `rubocop` is latest 0.45, `rubocop-rspec` is a bit outdated because it doesn't support ruby 2.0 since 1.5.1. 
Purpose of these gems is a normalization changes from different contributors based on https://github.com/bbatsov/ruby-style-guide. 
I did a small correction in a manual way and most changes with `-a` - auto correct option. 
Here 2 files `.rubocop.yml` - with common cops definition, `.rubocop-todo.yml` - includes files which aren't passed policies and they are candidates for refactoring. 
In `.travis.yml` rubocop starts before specs suite it makes tests failed if some of cops isn't passed.
Before commit we can use `bundle exec rubocop -aD` for small human mistakes auto correction.

### CODE REVIEW

**Comment by jnunemaker** [comment]
Sweet. Thanks for opening this. I've started to look at this, but it is pretty large so it is taking some time. I just wanted to update here so you didn't think I'd forgotten about it. I'm hoping to finish getting through it this week or next.

**Comment by lazebny** [comment]
Don't worry about time, it is really large. I hope it doesn't change logic and do only style fixes.

**Comment by AlexWheeler** [comment]
Rubocop is great. I think
`EnforcedStyleForMultiline consistent_comma`
`TrailingCommaInLiteral`
 have been pretty nice in Flipper and that @jnunemaker has mentioned preferring that style.

i.e.
```
a = [
  1,
  2,
]
```
vs.
```
a = [
  1,
  2
]
```
http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingCommaInLiteral

**Comment by lazebny** [comment]
Completely agree with you. It was changed and PR rebased.

**Comment by jnunemaker** [comment]
Sorry it took so long! There are a few things I want to tweak on this, but it is a great start and I really appreciate the work!

**Pull request merged**
