### PR TITLE
Remove Decorator

### PR DESCRIPTION
**Pull request by jnunemaker**
This removes decorator in favor of plain old ruby. Should expose the hierarchy of wrapped adapters, which is a common way to enhance flipper, and make it easier to debug adapter stacks.

One interesting tidbit is for instrumented adapter, you don't want to instrument the name of the adapter, but the name of the adapter you are wrapping, because no one wants to see instrumented everywhere in their stats. They want to see mysql or redis or whatever. 

I'll bump to 0.8 for flipper once this is ready to go as it is a breaking change.

cc @mislav @aroben @arthurnn for any thoughts/suggestions prior to me merging this

### CODE REVIEW

**Comment by aroben** [comment]
I implemented a decorator that only overrides #get. I guess with this new approach I'd need to pass other calls through explicitly. That's a little more work but probably worth the benefits.

-Adam




On Fri, Feb 26, 2016 at 7:11 AM -0800, "John Nunemaker" <notifications@github.com> wrote:












This removes decorator in favor of plain old ruby. Should expose the hierarchy of wrapped adapters, which is a common way to enhance flipper, and make it easier to debug adapter stacks.



One interesting tidbit is for instrumented adapter, you don't want to instrument the name of the adapter, but the name of the adapter you are wrapping, because no one wants to see instrumented everywhere in their stats. They want to see mysql or redis or whatever. 



I'll bump to 0.8 for flipper once this is ready to go as it is a breaking change.



cc @mislav @aroben for any thoughts/suggestions prior to me merging this



You can view, comment on, or merge this pull request online at:


  https://github.com/jnunemaker/flipper/pull/108

Commit Summary

  Switch instrumented from decorator to plain old ruby class
  Switch memoizable to plain old ruby class
  Switch operation logger to plain old ruby class from decorator
  Get rid of magic in operation logger
  Remove requires for decorator in classes that dont use it anymore
  Remove now unused decorator classes
  Update changelog
  Consistent usage of flipper adapter module in adapters


File Changes

  
    M
    Changelog.md
    (4)
  
  
    M
    lib/flipper/adapters/active_record.rb
    (2)
  
  
    D
    lib/flipper/adapters/decorator.rb
    (11)
  
  
    M
    lib/flipper/adapters/instrumented.rb
    (38)
  
  
    M
    lib/flipper/adapters/memoizable.rb
    (33)
  
  
    M
    lib/flipper/adapters/memory.rb
    (2)
  
  
    M
    lib/flipper/adapters/mongo.rb
    (2)
  
  
    M
    lib/flipper/adapters/operation_logger.rb
    (61)
  
  
    M
    lib/flipper/adapters/pstore.rb
    (2)
  
  
    M
    lib/flipper/adapters/redis.rb
    (2)
  
  
    D
    lib/flipper/decorator.rb
    (6)
  
  
    M
    spec/flipper/adapters/instrumented_spec.rb
    (6)
  
  
    M
    spec/flipper/adapters/memoizable_spec.rb
    (6)
  
  
    M
    spec/flipper/dsl_spec.rb
    (6)
  


Patch Links:

  https://github.com/jnunemaker/flipper/pull/108.patch
  https://github.com/jnunemaker/flipper/pull/108.diff

**Comment by mislav** [comment]
Looks alright! I'm glad to see the Decorator gone.

**Comment by arthurnn** [comment]
will check today.

**Comment by jnunemaker** [comment]
> I implemented a decorator that only overrides #get. I guess with this new approach I'd need to pass other calls through explicitly. That's a little more work but probably worth the benefits.

Yeah this is the downside. You could use def_delegators in ruby or delegate in rails to at least make delegating those others a bit less work.

**Comment by arthurnn** [comment]
👍

**Pull request merged**
